"""
services.py — Common port-to-service mapping database.

Provides a lookup dictionary of well-known TCP port numbers to their
associated service names and short descriptions.  Used by the scanner
for service identification when banner grabbing is unavailable.
"""

# fmt: off
COMMON_PORTS: dict[int, tuple[str, str]] = {
    7:     ("echo",            "Echo Protocol"),
    20:    ("ftp-data",        "FTP Data Transfer"),
    21:    ("ftp",             "FTP Control"),
    22:    ("ssh",             "Secure Shell"),
    23:    ("telnet",          "Telnet"),
    25:    ("smtp",            "Simple Mail Transfer Protocol"),
    26:    ("rsftp",           "RSFTP"),
    37:    ("time",            "Time Protocol"),
    43:    ("whois",           "WHOIS"),
    49:    ("tacacs",          "TACACS Login Host"),
    53:    ("dns",             "Domain Name System"),
    67:    ("dhcp-server",     "DHCP Server"),
    68:    ("dhcp-client",     "DHCP Client"),
    69:    ("tftp",            "Trivial File Transfer Protocol"),
    70:    ("gopher",          "Gopher Protocol"),
    79:    ("finger",          "Finger Protocol"),
    80:    ("http",            "HTTP Web Server"),
    81:    ("http-alt",        "HTTP Alternate"),
    88:    ("kerberos",        "Kerberos Authentication"),
    102:   ("iso-tsap",        "ISO-TSAP"),
    104:   ("dicom",           "DICOM Medical Imaging"),
    110:   ("pop3",            "Post Office Protocol v3"),
    111:   ("rpcbind",         "RPCBind / SunRPC"),
    113:   ("ident",           "Identification Protocol"),
    119:   ("nntp",            "Network News Transfer Protocol"),
    123:   ("ntp",             "Network Time Protocol"),
    135:   ("msrpc",           "Microsoft RPC / DCE Endpoint"),
    137:   ("netbios-ns",      "NetBIOS Name Service"),
    138:   ("netbios-dgm",     "NetBIOS Datagram Service"),
    139:   ("netbios-ssn",     "NetBIOS Session Service"),
    143:   ("imap",            "Internet Message Access Protocol"),
    161:   ("snmp",            "SNMP"),
    162:   ("snmptrap",        "SNMP Trap"),
    179:   ("bgp",             "Border Gateway Protocol"),
    194:   ("irc",             "Internet Relay Chat"),
    199:   ("smux",            "SNMP Unix Multiplexer"),
    220:   ("imap3",           "IMAP v3"),
    389:   ("ldap",            "Lightweight Directory Access Protocol"),
    443:   ("https",           "HTTPS / TLS"),
    445:   ("smb",             "SMB / Microsoft-DS"),
    464:   ("kpasswd",         "Kerberos Password Change"),
    465:   ("smtps",           "SMTP over TLS"),
    497:   ("retrospect",      "Retrospect Backup"),
    500:   ("isakmp",          "Internet Security Association (IKE)"),
    502:   ("modbus",          "Modbus Industrial Protocol"),
    512:   ("rexec",           "Remote Execution"),
    513:   ("rlogin",          "Remote Login"),
    514:   ("syslog",          "Syslog / Remote Shell"),
    515:   ("lpr",             "Line Printer Daemon"),
    520:   ("rip",             "Routing Information Protocol"),
    523:   ("ibm-db2",         "IBM DB2"),
    540:   ("uucp",            "UUCP"),
    548:   ("afp",             "Apple Filing Protocol"),
    554:   ("rtsp",            "Real Time Streaming Protocol"),
    587:   ("submission",      "SMTP Mail Submission"),
    593:   ("http-rpc-epmap",  "HTTP RPC Endpoint Mapper"),
    623:   ("ipmi",            "IPMI Remote Management"),
    631:   ("ipp",             "Internet Printing Protocol (CUPS)"),
    636:   ("ldaps",           "LDAP over TLS"),
    666:   ("doom",            "Doom Game / backdoor"),
    691:   ("ms-exchange",     "MS Exchange Routing"),
    873:   ("rsync",           "rsync File Sync"),
    902:   ("vmware-auth",     "VMware Authentication"),
    993:   ("imaps",           "IMAP over TLS"),
    995:   ("pop3s",           "POP3 over TLS"),
    1025:  ("msrpc",           "Microsoft RPC (high)"),
    1080:  ("socks",           "SOCKS Proxy"),
    1099:  ("rmiregistry",     "Java RMI Registry"),
    1194:  ("openvpn",         "OpenVPN"),
    1433:  ("mssql",           "Microsoft SQL Server"),
    1434:  ("mssql-monitor",   "MS SQL Monitor"),
    1521:  ("oracle",          "Oracle Database"),
    1723:  ("pptp",            "PPTP VPN"),
    1883:  ("mqtt",            "MQTT IoT Messaging"),
    1900:  ("upnp",            "Universal Plug and Play"),
    2049:  ("nfs",             "Network File System"),
    2082:  ("cpanel",          "cPanel"),
    2083:  ("cpanel-ssl",      "cPanel SSL"),
    2086:  ("whm",             "WebHost Manager"),
    2087:  ("whm-ssl",         "WebHost Manager SSL"),
    2100:  ("amiganetfs",      "Amiga Network FS"),
    2181:  ("zookeeper",       "Apache ZooKeeper"),
    2222:  ("ssh-alt",         "SSH Alternate"),
    2375:  ("docker",          "Docker REST API (unencrypted)"),
    2376:  ("docker-tls",      "Docker REST API (TLS)"),
    3000:  ("grafana",         "Grafana / Node.js Dev"),
    3306:  ("mysql",           "MySQL Database"),
    3389:  ("rdp",             "Remote Desktop Protocol"),
    3690:  ("svn",             "Subversion"),
    4000:  ("remoteanything",  "Remote Anything"),
    4443:  ("https-alt",       "HTTPS Alternate"),
    4444:  ("metasploit",      "Metasploit / Blaster worm"),
    4567:  ("sinatra",         "Sinatra / Tram"),
    4848:  ("glassfish",       "GlassFish Admin"),
    5000:  ("upnp",            "UPnP / Flask Dev"),
    5432:  ("postgresql",      "PostgreSQL Database"),
    5555:  ("adb",             "Android Debug Bridge"),
    5601:  ("kibana",          "Kibana Dashboard"),
    5672:  ("amqp",            "RabbitMQ / AMQP"),
    5900:  ("vnc",             "VNC Remote Desktop"),
    5984:  ("couchdb",         "CouchDB"),
    6379:  ("redis",           "Redis Key-Value Store"),
    6443:  ("kubernetes",      "Kubernetes API Server"),
    6667:  ("irc",             "IRC"),
    7001:  ("weblogic",        "Oracle WebLogic"),
    7474:  ("neo4j",           "Neo4j Graph Database"),
    8000:  ("http-alt",        "HTTP Alternate / Dev Server"),
    8008:  ("http-alt",        "HTTP Alternate"),
    8080:  ("http-proxy",      "HTTP Proxy / Tomcat"),
    8081:  ("http-alt",        "HTTP Alternate"),
    8443:  ("https-alt",       "HTTPS Alternate / Tomcat SSL"),
    8888:  ("http-alt",        "HTTP Alternate / Jupyter"),
    9000:  ("php-fpm",         "PHP-FPM / SonarQube"),
    9090:  ("prometheus",      "Prometheus / WebSM"),
    9092:  ("kafka",           "Apache Kafka"),
    9200:  ("elasticsearch",   "Elasticsearch HTTP"),
    9300:  ("elasticsearch",   "Elasticsearch Transport"),
    9418:  ("git",             "Git Protocol"),
    9999:  ("abyss",           "Abyss Web Server"),
    10000: ("webmin",          "Webmin Admin Panel"),
    11211: ("memcached",       "Memcached"),
    15672: ("rabbitmq-mgmt",   "RabbitMQ Management"),
    27017: ("mongodb",         "MongoDB"),
    27018: ("mongodb",         "MongoDB Shard"),
    28017: ("mongodb-web",     "MongoDB Web Status"),
    50000: ("sap",             "SAP Management Console"),
    50070: ("hadoop-nn",       "Hadoop NameNode"),
}
# fmt: on

# Sorted list of ports commonly scanned in a "top-N" sweep.
TOP_PORTS: list[int] = sorted(COMMON_PORTS.keys())


def lookup(port: int) -> tuple[str, str]:
    """Return (service_name, description) for a port, or a default tuple."""
    return COMMON_PORTS.get(port, ("unknown", ""))


def top_n_ports(n: int) -> list[int]:
    """Return the first *n* ports from the ranked common-ports list."""
    return TOP_PORTS[:n]
